# 1 - Crie um Dockerfile utilizando a imagem chuanwen/cowsay.
# 2 - Agora defina um ENTRYPOINT para a execução do comando.
# 3 - Lembre-se que com ele, diferente do CMD, o comando não poderá ser sobrescrito com o docker run. Porém, conseguiremos passar parâmetros ao binário. Exploraremos esse recurso para poder passar a mensagem.
# 4 - Utilize o CMD para definir uma mensagem padrão.

FROM chuanwen/cowsay
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "VQV TRYBE!" ]



